spring:
  application:
    name: springboot

  datasource:
    url: jdbc:mysql://localhost:3306/db_cafe_management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  # logging:
  #   level:
  #     org.springframework.jdbc.core: DEBUG
  #     root: DEBUG
  devtools:
    restart:
      enabled: true # Bật hot reload
    livereload:
      enabled: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
